In [25]:
import pandas as pd

In [26]:
dados = pd.read_csv('Customer-Churn.csv')
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [27]:
traducao_dic = {
    'Sim' : 1, 'Nao': 0
}

dadosmodificados = dados [['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0           1            0             0                1      0
1           0            0             1                0      0
2           0            0             1                1      1
3           0            0             0                0      0
4           0            0             1                1      1
...       ...          ...           ...              ...    ...
7038        1            1             1                1      0
7039        1            1             1                1      0
7040        1            1             0                1      0
7041        1            0             1                1      1
7042        0            0             1                1      0

[7043 rows x 5 columns]

In [28]:
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)
dados_final

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0           1            0             0                1      0            0   
1           0            0             1                0      0            0   
2           0            0             1                1      1            0   
3           0            0             0                0      0            0   
4           0            0             1                1      1            0   
...       ...          ...           ...              ...    ...          ...   
7038        1            1             1                1      0            0   
7039        1            1             1                1      0            0   
7040        1            1             0                1      0            0   
7041        1            0             1                1      1            1   
7042        0            0             1                1      0            0   

      MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                   1        29.85                            0   
1                  34        56.95                            1   
2                   2        53.85                            1   
3                  45        42.30                            0   
4                   2        70.70                            1   
...               ...          ...                          ...   
7038               24        84.80                            0   
7039               72       103.20                            0   
7040               11        29.60                            0   
7041                4        74.40                            0   
7042               66       105.65                            1   

      VariasLinhasTelefonicas_SemServicoTelefonico  \
0                                                1   
1                                                0   
2                                                0   
3                                                1   
4                                                0   
...                                            ...   
7038                                             0   
7039                                             0   
7040                                             1   
7041                                             0   
7042                                             0   

      VariasLinhasTelefonicas_Sim  ServicoDeInternet_DSL  \
0                               0                      1   
1                               0                      1   
2                               0                      1   
3                               0                      1   
4                               0                      0   
...                           ...                    ...   
7038                            1                      1   
7039                            1                      0   
7040                            0                      1   
7041                            1                      0   
7042                            0                      0   

      ServicoDeInternet_FibraOptica  ServicoDeInternet_Nao  \
0                                 0                      0   
1                                 0                      0   
2                                 0                      0   
3                                 0                      0   
4                                 1                      0   
...                             ...                    ...   
7038                              0                      0   
7039                              1                      0   
7040                              0                      0   
7041                              1                      0   
7042                              1                      0   

      SegurancaOnline_Nao  SegurancaOnline_SemServicoDeInternet  \
0                       1                     

In [29]:
pd.set_option('display.max_columns', 39)
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

In [30]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [31]:
x = dados_final.drop('Churn', axis=1)
y = dados_final['Churn']

In [32]:
from sklearn.preprocessing import StandardScaler

norm = StandardScaler()
x_normalizado = norm.fit_transform(x)
x_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [33]:
xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns=x.columns))
xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [34]:
import numpy as np

a = xmaria_normalizado
b = x_normalizado[0]

In [35]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [36]:
np.sqrt(np.sum(np.square(a-b)))

9.169282435541762

In [37]:
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x_normalizado, y, test_size=0.3, random_state=123)

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(metric='euclidean')
knn.fit(x_treino, y_treino)
predict_knn = knn.predict(x_teste)

In [39]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB(binarize=0.44)
bnb.fit(x_treino, y_treino)
predict_bnb = bnb.predict(x_teste)

In [40]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_teste, predict_knn))
print(confusion_matrix(y_teste, predict_bnb))
print(confusion_matrix(y_teste, predict_knn))

[[1304  219]
 [ 317  273]]
[[1059  464]
 [ 120  470]]
[[1304  219]
 [ 317  273]]


In [41]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_teste, predict_knn) * 100)
print(accuracy_score(y_teste, predict_bnb) * 100)

74.6332229058211
72.36157122574538


In [42]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc.fit(x_treino, y_treino)
predict_dtc = dtc.predict(x_teste)
predict_dtc

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [43]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_teste, predict_knn) * 100)
print(accuracy_score(y_teste, predict_bnb) * 100)
print(accuracy_score(y_teste, predict_dtc) * 100)

74.6332229058211
72.36157122574538
73.30809275911027


In [44]:
from sklearn.metrics import precision_score

print(precision_score(y_teste, predict_knn) * 100)
print(precision_score(y_teste, predict_bnb) * 100)
print(precision_score(y_teste, predict_dtc) * 100)

55.487804878048784
50.32119914346895
52.264808362369344


In [45]:
from sklearn.metrics import recall_score

print(recall_score(y_teste, predict_knn) * 100)
print(recall_score(y_teste, predict_bnb) * 100)
print(recall_score(y_teste, predict_dtc) * 100)

46.271186440677965
79.66101694915254
50.847457627118644


In [46]:
# Importando os métodos para calcular as métricas
from sklearn.metrics import recall_score, precision_score, f1_score

# Dados ofericidos na questão
diagnostico_predito = [0,0,0,0,1,1,1,1,0,1,0,1]
diagnostico_real = [1,1,0,0,1,1,1,0,1,0,1,0]

# Calculando as métricas
print(f"Recall = {round(recall_score(diagnostico_real, diagnostico_predito), 3)}")
print(f"f1-score = {round(f1_score(diagnostico_real, diagnostico_predito), 3)}")

Recall = 0.429
f1-score = 0.462


In [47]:
print('Modelo KNN:', precision_score(y_teste, predict_knn))
print('Modelo Bernoulli de Naive Bayes:', precision_score(y_teste, predict_bnb))
print('Modelo Àrvore de Decisão:', precision_score(y_teste, predict_dtc))

Modelo KNN: 0.5548780487804879
Modelo Bernoulli de Naive Bayes: 0.5032119914346895
Modelo Àrvore de Decisão: 0.5226480836236934
